title: Qixiang Li's Homepage
page-top-title: Qixiang Li
top-section-bg-text: Innovation, mobility, technology & geography
home-subtitle: Qixiang Li&ensp;|&ensp;李祺祥
copyright-text: '&copy; Qixiang Li 2025-2026. All Rights Reserved.'
